language: minimal

services: docker

install:
    - travis_retry make build

script:
    - make all-tests

if: |
    branch = master OR \
    branch =~ /^[0-9\.]+$/ OR \
    tag IS present OR \
    type = pull_request
