version: '3.4'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        dev: ""
        simulate_removal: "-s"
    image: libero/search_dev:${IMAGE_TAG:-master}
    volumes:
      - ..:/srv/app
    command: "flask run --host=0.0.0.0"
    healthcheck:
        test: ["CMD", "nc", "-z", "localhost", "5000"]
        interval: 5s
    ports:
      - "5000:5000"
    env_file:
      - dev.env
