version: '3.4'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        dev: "--no-dev"
        simulate_removal: ""
    image: libero/search:${IMAGE_TAG:-master}
    command: uwsgi --ini=uwsgi.ini
    volumes:
      - ./uwsgi.ini:/srv/app/uwsgi.ini
  web:
    image: nginx:1.15.5-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
