version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        dev: ""
    image: libero/search_dev:${IMAGE_TAG:-master}
    volumes:
      - ..:/srv/app
    command: "flask run --host=0.0.0.0"
    ports:
      - "5000:5000"
    env_file:
      - dev.env
